name: Update README

on:
  schedule:
    - cron: "0 */12 * * *" # cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update Recent Activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
