name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    permissions:
      contents: write   # Importante para que GITHUB_TOKEN pueda modificar el repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update Recent Activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GH_USERNAME: TU_USUARIO_GITHUB
          CONFIG_FILE: .github/recent-activity.config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # 🔑 Aquí se pasa el token
